development:
  adapter: postgresql
  database: dockwa_managed_accounts_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: dockwa_managed_accounts_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dockwa_managed_accounts
  pool: 5
  timeout: 5000
